### ISSUE TITLE
Issue walkthrough

### ISSUE THREAD

**Issue by phorcys420** [coder/codercord#1]
I was thinking it would be interesting to take users through a little series of questions when they create a new thread in #help

## Flow

1. Choose issue category : Help needed, Bug report, Feature request
if feature request or bug report then probably redirect them to GH issues and lock thread.
2. What product is this issue related to ? Coder v1, Coder v2, code-server
3. What platform are you running the product on ? Linux, Windows, macOS
4. What runtime are you using to run the product ? Docker, SystemD (depending on platform)
5. Have you posted logs ? if no, please do
6. Tell users to mention anything else that could matter (product version, etc)
7. The bot posts a summary of the issue and pins it

For each category, a tag should be added to the issue.

---

I think the message should delete itself after 5 minutes of inactivity.

## Implementation 1 (discarded)

~~Have the user run a command that shows a [modal](https://user-images.githubusercontent.com/57866459/216955414-b799e2a9-51f5-43cb-b984-6df448a1a9f3.png) to them.
This is nice but it requires running a command, which makes the UX poorer.~~

## Implementation 2 (choosen)

Sending a self-editing message on every thread creation that contains [action rows](https://user-images.githubusercontent.com/57866459/216955833-33faf1b7-8328-4a45-90e3-8dbc3f073cd1.png)

I think this gives better UX but we might get the bot rate-limited if too much threads are created at once.

---

## Roadmap
- [ ] Action row components
   - [x] Base components and questions
   - [ ] "Other" entries for every question
   - [x] Styled components (emojis in action rows)
- [x] Action row events
   - [x] Item selection is handled properly and state-agnostic
   - [x] Only the owner of the post and admins can use the walkthrough
- [x] Walkthrough is sent on post creation
   - [x] nyxx-discord/nyxx#440
- [ ] Back button under action rows so you can correct input mistakes
- [x] Summary message
   - [x] The thread name is displayed
   - [x] Infos from the questions are displayed
   - [x] The summary is pinned automatically
   - [x] Summary is good-looking (maybe use embeds?)
   - [x] Log locations are indicated to the user
   - [x] The pin alert message is automatically deleted

**Comment by matifali** [comment]
also, add instructions on how to get logs. like showing them commands and asking users to paste the output they get from running each command.

**Comment by phorcys420** [comment]
> add instructions on how to get logs. like showing them commands and asking users to paste the output they get from running each command.

yes that's a good idea, i will also add a "platform" dropdown so that it gives the appropriate log locations.

**Comment by phorcys420** [comment]
Here is a quick prototype i sat up.

![Discord_2GnP8VvJrp](https://user-images.githubusercontent.com/57866459/218208127-d114b9a4-38b7-4251-a066-b1731f3f8541.gif)

It currently posts twice because I am unable to distinguish between thread creation and thread join due to an issue in the library's repo (https://github.com/nyxx-discord/nyxx/issues/440)

**Comment by phorcys420** [comment]
Here is an updated version of the flow.
I will also add icons for other dropdowns, I was just lazy.

![Discord_TEVmBvKZAI](https://user-images.githubusercontent.com/57866459/218332936-ada64822-b4cd-406f-a68a-f3b42334b0b7.gif)

**Comment by phorcys420** [comment]
here's how it looks now, it will also be the first rollout think

![Discord_ujZlx8NtGR](https://user-images.githubusercontent.com/57866459/221373937-88bd4fe4-a4b4-4026-949b-a14e1e620ea6.gif)

**Comment by matifali** [comment]
Many people who discover coder from GitHub do not know abut v1 and v2. They only know coder.

**Comment by phorcys420** [comment]
:+1:
I could also add the repo name ?
I think it's sensible to keep the v1 entry until the sunset is complete though
![Discord_UNlEhqAvk8](https://user-images.githubusercontent.com/57866459/221374531-b44fb524-b48e-46f7-87bd-fc149105ad30.gif)

This is kind of too much though, maybe I should just get rid of v1 altogether ?

**Comment by matifali** [comment]
yeah I suggest removing v1 as that is supported on slack.
